version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: persona-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./PersonaBACKEND
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/persona-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./personafront
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres-data:
